version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet build src/CloudHRMS.csproj
  post_build:
    commands:
      - dotnet publish -r linux-x64 src/CloudHRMS.csproj
artifacts:  
  files:
    - src/bin/Debug/net8.0/linux-x64/publish/**/*
  discard-paths: yes